### ISSUE TITLE
Example of virtuak repeater

### ISSUE THREAD

**Issue by elvisbegovic** [Klaster1/timer2#15]
Can you please get example of use of your ported virtual repeater?

**Comment by Klaster1** [comment]
Sure. The repeater is used in two places: [here ](https://github.com/Klaster1/timer2/blob/master/src/components/games-list/template.html#L55-L70) and [here](https://github.com/Klaster1/timer2/blob/master/src/components/game-detail/template.html#L26-L47). First, you have to wrap everything with `md-virtual-repeat-container` component. Then use `mdVirtualRepeat` attribute directive just like `ngFor`:

```
*mdVirtualRepeat="
	let game of games$|async;
	itemSize: 48;
	trackBy: trackBy;
"
```
If you are going to use repeater in another project, feel free to pluck out it's module and modify the code for particular needs. At the very least, the code has to be compiled into compatible style and JS, unless your project uses same/similar toolchain, which I doubt.

**Comment by elvisbegovic** [comment]
dammage your virtual repeater have a lot of error when convert .js file into .ts
